### ISSUE TITLE
Unable to parse response from server since Selenium Java 4.5.1 with LitteProxy (BrowserUP-Proxy)

### ISSUE THREAD

**Issue by derRichter** [valfirst/browserup-proxy#160]
### What happened?

Hi,

since Selenium-Java ver. 4.5.1 and up to 4.5.3, maybe with the new PortPropper-Feature, we have no working connection anymore over LitteProxy [(last version of BrowserUp-Proxy)](https://github.com/valfirst/browserup-proxy/) if the ChromeDriver eg. the Chromium in Headless-Mode.
If the Headless-Mode turned off, there are no problems with the connection.

When we use Selenium-Java 4.5.0 or older all fine in Headless-Mode with the Proxy-Connection.
Without Proxy-Connection also no Problems, only since Version 4.5.1 with Proxy the we get this responce as a html-website:

"Unable to parse response from server"
(see the chromedriver-logs)

What can we do to use the headless-mode?

greats

### How can we reproduce the issue?
[chromedriver-log_selenium-4.5.3-over-browserupproxy_headlessmode-on.txt](https://github.com/SeleniumHQ/selenium/files/9886936/chromedriver-log_selenium-4.5.3-over-browserupproxy_headlessmode-on.txt)

```shell
Use Selenium-Java ver. 4.5.1 or newer with BrowserUp-Proxy as proxy (and aktivated Headless-Mode) the connection over the proxy is not working.
"Unable to parse response from server"
```

### Relevant log output

```shell
1666946167.460][INFO]: [26c81179a9a5f201506b413ded982055] COMMAND Navigate {
   "url": "https://meine.santander.de/"
}
[1666946167.460][INFO]: Waiting for pending navigations...
[1666946167.460][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=19) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "expression": "1"
}
[1666946167.461][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=19) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}
[1666946167.461][INFO]: Done waiting for pending navigations. Status: ok
[1666946167.461][DEBUG]: DevTools WebSocket Command: Page.navigate (id=20) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "url": "https://meine.santander.de/"
}
[1666946167.464][DEBUG]: DevTools WebSocket Event: Network.requestWillBeSent (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "documentURL": "https://meine.santander.de/",
   "frameId": "A2DEB70026F4443A5F9F4552CD56BB27",
   "hasUserGesture": false,
   "initiator": {
      "type": "other"
   },
   "loaderId": "652EFF04148AF1013A80091645D22E58",
   "redirectHasExtraInfo": false,
   "request": {
      "headers": {
         "Upgrade-Insecure-Requests": "1",
         "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.0 Safari/537.36"
      },
      "initialPriority": "VeryHigh",
      "isSameSite": true,
      "method": "GET",
      "mixedContentType": "none",
      "referrerPolicy": "strict-origin-when-cross-origin",
      "url": "https://meine.santander.de/"
   },
   "requestId": "652EFF04148AF1013A80091645D22E58",
   "timestamp": 952391.648372,
   "type": "Document",
   "wallTime": 1666946167.463118
}
[1028/103607.510720:WARNING:resource_bundle.cc(450)] locale_file_path.empty() for locale de-DE
[1666946169.107][DEBUG]: DevTools WebSocket Event: Network.requestWillBeSentExtraInfo (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "associatedCookies": [  ],
   "connectTiming": {
      "requestTime": 952391.649863
   },
   "headers": {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "de-DE",
      "Connection": "keep-alive",
      "Host": "meine.santander.de",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "none",
      "Sec-Fetch-User": "?1",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.0 Safari/537.36"
   },
   "requestId": "652EFF04148AF1013A80091645D22E58"
}
[1666946169.204][DEBUG]: DevTools WebSocket Event: Network.responseReceivedExtraInfo (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "blockedCookies": [  ],
   "headers": {
      "content-length": "36",
      "content-type": "text/html; charset=utf-8",
      "date": "Fri, 28 Oct 2022 08:36:09 GMT",
      "via": "1.1 BrowserUpProxy"
   },
   "headersText": "HTTP/1.1 502 Bad Gateway\r\ncontent-length: 36\r\ncontent-type: text/html; charset=utf-8\r\nvia: 1.1 BrowserUpProxy\r\ndate: Fri, 28 Oct 2022 08:36:09 GMT\r\n\r\n",
   "requestId": "652EFF04148AF1013A80091645D22E58",
   "resourceIPAddressSpace": "Unknown",
   "statusCode": 502
}
```

### Operating System

Windows 10, macOS 10.14

### Selenium version

Selenium Java 4.5.1, 4.5.2, 4.5.3

### What are the browser(s) and version(s) where you see this issue?

Chromium 107.0.5304.68

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver-Version 107.0.5304.62

### Here is my Test-Case

[little.tester.zip](https://github.com/valfirst/browserup-proxy/files/9892316/little.tester.zip)

**Comment by derRichter** [comment]
its the same, and with the new browserup-proxy 2.2.4 (but the deps on jar-download.com are not included?) with the same netty-version in selenium 4.5.3, is the same issue now without headless-mode also.
there is any conflict?

**Comment by valfirst** [comment]
@derRichter does the solution proposed in https://github.com/SeleniumHQ/selenium/issues/11186 work for you?

**Comment by derRichter** [comment]
no, is not working.
It is poosible there is a conflict with the new netty in BUP and the old Netty in the current LittleProxy 2.0.13?
since the newer Netty is included in Selenim 4.5.1 and higher or BUP 2.2.4 the proxy-connection is not working anymore and the result is "Bad Gateway" with "Unable to parse response from server" or Redirect-Errors.

With Selenium 4.5.0 and BUP 2.2.3 is the same connection working fine:
https://meine.santander.de/olb

**Comment by derRichter** [comment]
i tested with the new selenium 4.6.0 and is the same problem. (no response from proxy, "Unable to parse response from server".
Or in other constelations Redirects not working anymore: Test https://www.google.com that normaly redirect to the privacy-settings on first visit.

Looks very strong like BrowserUp-Proxy or i think LittleProxy don't work with Netty Version 4.1.84.

On my testcase (on my Programm) i have dirffents plugins (browserup-proxy, selenium, pdfbox, etc...)

If i use BrowserUpProxy-Package "2.2.3" in my classpath (Netty 4.1.82) works with Selenium-Java-Package 4.5.0 (Netty 4.1.79).
If i Update Selenium over since 4.5.1 (or 4.6.0) with Netty 4.1.84 that brokes the function of the Proxy.
If i delete the Netty-Classes with version 4.1.84 from the Selenium-Deps-Libs-Folder excluding "netty-reactive-streams-2.0.4.jar" then the connection is working like a carme.

If i Update to BrowserUp-Proxy 2.2.4 with Netty 4.1.84 included an leave the libs in selenium, i got redirect errors like https://www.google.com or https://meine.santander.com. Is not redirecting anymore.

Looks very strong like BrowserUp-Proxy or i think LittleProxy don't work with Netty Version 4.1.84.

(With Selenium-Java standalone works without problems.)

Do you know also why "the deps on jar-download.com are not included?" in the browserup-proxy-"core" package?
And is not "verified" tagged release from you?

Thanks for you work! and this poject! Great!

**Comment by valfirst** [comment]
it might be related to https://github.com/LittleProxy/LittleProxy/issues/179

**Comment by valfirst** [comment]
`2.2.5` is released and available for use.

As for `jar-download.com` I don't known how it works unfortunately.

**Comment by derRichter** [comment]
thank you very much for your work.
The new Version 2.2.5 work great with Selenium-Java 4.6.0.
It is probably necessary to delete the 14 io.netty jar files in the selenium-java packet or to replace them with version 4.1.82 to avoid this error.
And i think it's better to upgrade the three jars from com.fasterxml.jackson.core to version 2.14.

greats
